"""Stable external ComfyUI model-folder mapping across Windows and Linux."""

from __future__ import annotations

import json
import os
from pathlib import Path


IS_WINDOWS = os.name == "nt"
WINDOWS_DEFAULT = Path(r"C:\ComfyUI_windows_portable\ComfyUI\models")
LINUX_DEFAULT = Path.home() / "ComfyUI" / "models"
CONFIG_NAME = "main_server_extra_model_paths.yaml"


class ModelPathError(RuntimeError):
    pass


def default_model_root() -> str:
    return str(WINDOWS_DEFAULT if IS_WINDOWS else LINUX_DEFAULT)


def resolve_model_root(value: str) -> Path:
    raw = os.path.expandvars(os.path.expanduser(str(value or default_model_root()).strip()))
    if not raw or not os.path.isabs(raw):
        raise ModelPathError("ComfyUI 모델 폴더는 절대 경로여야 합니다")
    return Path(os.path.normpath(raw))


MODEL_FOLDERS: dict[str, tuple[str, ...]] = {
    "checkpoints": ("checkpoints", "StableDiffusion"),
    "configs": ("configs",),
    "loras": ("loras", "Lora", "LyCORIS"),
    "vae": ("vae",),
    "text_encoders": ("text_encoders", "clip"),
    "diffusion_models": ("unet", "diffusion_models"),
    "clip_vision": ("clip_vision",),
    "style_models": ("style_models",),
    "embeddings": ("embeddings", "TextualInversion"),
    "diffusers": ("diffusers",),
    "vae_approx": ("vae_approx", "ApproxVAE"),
    "controlnet": ("controlnet", "ControlNet", "T2IAdapter"),
    "gligen": ("gligen",),
    "upscale_models": ("upscale_models", "ESRGAN", "RealESRGAN", "SwinIR", "BSRGAN"),
    "latent_upscale_models": ("latent_upscale_models",),
    "hypernetworks": ("hypernetworks", "Hypernetwork"),
    "photomaker": ("photomaker",),
    "classifiers": ("classifiers",),
    "model_patches": ("model_patches",),
    "audio_encoders": ("audio_encoders",),
    "background_removal": ("background_removal", "RMBG", "BiRefNet"),
    "frame_interpolation": ("frame_interpolation",),
    "geometry_estimation": ("geometry_estimation",),
    "optical_flow": ("optical_flow",),
    "detection": ("detection", "AfterDetailer"),
    # JH Auto Image Feed registers this category and recursively resolves
    # bbox/*.pt and segm/*.pt through folder_paths.  Mapping only the generic
    # detection folders leaves these workflow model references unresolved.
    "ultralytics": ("ultralytics",),
}


def ensure_model_config(comfyui_dir: str, model_root: str) -> tuple[Path, Path]:
    directory = Path(comfyui_dir)
    if not (directory / "main.py").is_file():
        raise ModelPathError(f"ComfyUI 설치 폴더가 아닙니다: {directory}")
    resolved = resolve_model_root(model_root)
    if not resolved.is_dir():
        raise ModelPathError(f"ComfyUI 모델 폴더를 찾을 수 없습니다: {resolved}")

    lines = ["# Generated by main_server. Edit the integrated path setting instead.", "main_server_models:"]
    lines.append(f"  base_path: {json.dumps(str(resolved), ensure_ascii=False)}")
    lines.append("  is_default: true")
    for key, folders in MODEL_FOLDERS.items():
        existing = [folder for folder in folders if (resolved / folder).is_dir()]
        selected = existing or [folders[0]]
        if len(selected) == 1:
            lines.append(f"  {key}: {json.dumps(selected[0], ensure_ascii=False)}")
        else:
            lines.append(f"  {key}: |")
            lines.extend(f"    {folder}" for folder in selected)
    config_path = directory / CONFIG_NAME
    temporary = config_path.with_suffix(config_path.suffix + ".tmp")
    temporary.write_text("\n".join(lines) + "\n", encoding="utf-8")
    os.replace(temporary, config_path)
    return config_path, resolved
